name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: push docker image
      run: docker push
    # - name: push docker image
    #   uses: docker/push-action@v5
    #   with:
    #      context: .
    #      platforms: linux/amd64,linux/arm64
    #      push: true
    #      tags: |
    #         syed-mudassir871/app:latest
    #         syed-mudassir871/app:1.0.0
    #         ghcr.io/syed-mudassir871/app:latest
    #         ghcr.io/syed-mudassir871/app:1.0.0
         
      
      
